### ISSUE TITLE
[QUESTION] State of rusty-machine

### ISSUE THREAD

**Issue by k0pernicus** [AtheMathmo/rusty-machine#180]
Hello,

I plan to use Rust for my PhD thesis, especially to re-implement my Python prototype with something more safe.
`rusty-machine` seems perfect to me, but I don't see any contribution since February...
Is the library still updated?

I am open to contribute to `rusty-machine`, especially to test or improve code for a first time, and implement new methods as a second part.

**Comment by AtheMathmo** [comment]
Hey @k0pernicus .

Since February my schedule has gotten a lot more intense than previously. As a result I am not able to contribute as much time as before. However, I still want to continue developing rusty-machine and hopefully soon will have enough time to shepherd some of the open issues and PRs.

Sorry that I can't give a more concrete answer right now.

**Comment by k0pernicus** [comment]
Hey @AtheMathmo,

No problem :-)
I will try to solve simple issues at first, and make PR to help you with this project.

Good luck!
