### ISSUE TITLE
Adding row iterators

### ISSUE THREAD

**Issue by AtheMathmo** [AtheMathmo/rusty-machine#48]
It would be nice to be able to iterate over the rows in our matrices.

This will also allow us to make some optimizations for binary operation assignment on `MatrixSliceMut`. We cannot (easily) vectorize the whole operation as the data is not contiguous - but the rows are. If we can iterate over the rows then we can vectorize the operation on each row.

**Comment by zackmdavis** [comment]
Can we get column iterators, too?

(Last night, when I was starting to write the eigenvectors test for #47 before I ran out of time, I found myself wanting to iterate over the columns of the matrix that we return from `eigendecomp` so that I could assert that for each eigenvalue λ_i and corresponding eigenvector v_i, A*v_i = λ_i * v_i, which seemed more meaningful than asserting that the eigenvector is componentwise identical to some expected value, but I didn't see a column iterator anywhere.)

**Comment by AtheMathmo** [comment]
Column iterators are less easy (at least to do efficiently). Rows are ok because we store the matrix in row-major order - we don't need to copy any of the data. To do a column iterator we need to be able to copy the data and place it into contiguous slices.

I do agree though that it would probably be good to have despite this. I'll see if I can figure out a nice way to do it :). We could even be hacky and do an in-place transpose (which I still need to write) and then return a Row iterator...
